stages:
  get_data:
    cmd: python model_training/dataset.py
    deps:
    - model_training/dataset.py
    outs:
    - data/raw/a1_RestaurantReviews_HistoricDump.tsv
  pre_process:
    cmd: python model_training/preprocessing.py
    deps:
    - model_training/preprocessing.py
    - data/raw/a1_RestaurantReviews_HistoricDump.tsv
    outs:
    - data/processed/a1_RestaurantReviews_HistoricDump.tsv
  transform_data:
    cmd: python model_training/features.py
    deps:
    - model_training/features.py
    - data/processed/a1_RestaurantReviews_HistoricDump.tsv
    outs:
    - data/processed/features_test.npy
    - data/processed/features_train.npy
    - data/processed/labels_test.npy
    - data/processed/labels_train.npy
    - models/c1_BoW_Sentiment_Model.pkl
  updating_params:
    cmd: python model_training/modeling/ensure_versioning.py
    deps:
    - model_training/modeling/ensure_versioning.py
    outs:
    - params.yaml
  train_model:
    cmd: python model_training/modeling/train.py
    deps:
      - model_training/modeling/train.py
      - data/processed/features_train.npy
      - data/processed/labels_train.npy
      - dynamic_version.txt
    params:
      - version  
    outs:
      - models/${version}/${version}_Sentiment_Model.pkl