name: ML Auto-Test

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths-ignore:
      - README.md

jobs:
  run_tests:
    if: github.actor != 'github-actions'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.OP_TOKEN }}

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Fetch all tags
        run: git fetch --tags

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install coverage pytest flake8 isort black pylint

      - name: Run format
        run: make format

      - name: Run lint
        run: make lint

      - name: Download NLTK data
        run: |
          python -m nltk.downloader stopwords wordnet omw-1.4

      - name: Download dataset
        run: python -m model_training.dataset

      - name: Run tests with coverage (detailed output)
        run: |
          echo "Running unit tests..."
          export PYTHONPATH=$(pwd):$PYTHONPATH
          coverage run --rcfile=.coveragerc -m pytest -v --tb=short --durations=10 tests | tee test_output.txt

          echo "Running metamorphic robustness test..."
          coverage run --rcfile=.coveragerc --append tests/test_metamorphic.py \
            --input data/processed/a1_RestaurantReviews_HistoricDump.tsv \
            --model-version test_model_dev \
            | tee metamorphic_output.txt

          coverage report --rcfile=.coveragerc -m > coverage.txt

      - name: Show coverage summary
        run: coverage report --rcfile=.coveragerc -m
      
      - name: Debug check for metrics.json
        run: |
          echo "Current directory: $(pwd)"
          ls -lah
          cat $GITHUB_WORKSPACE/metrics.json || echo "metrics.json not found!"

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Extract and update coverage
        run: |
          COVERAGE=$(tail -n1 coverage.txt | awk '{print $NF}')
          echo "Coverage: ${COVERAGE}"
          sed -i "s|<!-- COVERAGE -->.*|<!-- COVERAGE --> Coverage: ${COVERAGE}|" README.md
    
      - name: Extract test adequacy info and update README
        run: |
          # Remove old section
          sed -i '/<!-- METRICS START -->/,/<!-- METRICS END -->/d' README.md

          echo "<!-- METRICS START -->" >> README.md
          echo "" >> README.md

          # Group by category
          for cat in DATA_AND_FEATURES MODEL_DEVELOPMENT INFRASTRUCTURE_TESTING MONITORING_TESTING; do
            echo "#### ${cat^}" >> README.md
            echo "" >> README.md
            echo "| Metric | Value | Notes |" >> README.md
            echo "|--------|-------|---------|" >> README.md
            jq -r \
              --arg cat "$cat" \
              '. as $root | to_entries
               | map(select(.value.category == $cat))
               | .[] 
               | "| \(.key) | \(.value.value) | \(.value.message // "-") |"' \
               metrics.json >> README.md
            echo "" >> README.md
          done

          echo "<!-- METRICS END -->" >> README.md

      - name: Insert selected badges below README title
        run: |
          # Define metrics to show as badges
          METRICS="test_coverage model_accuracy pylint_score code_quality tests_passed"

          # Backup original README
          cp README.md README_backup.md

          # Extract badges markdown for selected metrics
          BADGES=""
          for metric in $METRICS; do
            # Extract value from metrics.json (if metric not found, skip)
            VALUE=$(jq -r --arg m "$metric" '.[$m].value // empty' metrics.json)
            if [ -z "$VALUE" ]; then
              continue
            fi

            # Normalize label and value for URL
            LABEL=$(echo "$metric" | sed 's/_/%20/g')
            VAL_ENC=$(echo "$VALUE" | sed 's/ /%20/g')

            # Determine color
            RAW_VAL=$(echo "$VALUE" | sed 's/%//')
            if [[ "$RAW_VAL" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
              NUM_VAL=$(printf "%.0f" "$RAW_VAL")
              if (( NUM_VAL >= 90 )); then
                COLOR="brightgreen"
              elif (( NUM_VAL >= 75 )); then
                COLOR="yellow"
              else
                COLOR="red"
              fi
            else
              COLOR="blue"
            fi

            BADGES="${BADGES}![${metric}](https://img.shields.io/badge/${LABEL}-${VAL_ENC}-${COLOR}?label=${LABEL}) "
          done

          # Insert badges below first non-empty line (usually title) in README.md
          awk -v badges="$BADGES" '
            NR==1 {print; print ""; print badges; next}
            {print}
          ' README_backup.md > README.md


      - name: Commit and push updated README
        run: |
          git add README.md
          git diff --cached --quiet || git commit -m "ci: update README with test results"
          git push
