name: ML Auto-Test

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths-ignore:
      - README.md

jobs:
  run_tests:
    if: github.actor != 'github-actions'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.OP_TOKEN }}

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Fetch all tags
        run: git fetch --tags

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install coverage pytest flake8 isort black pylint

      - name: Run format
        run: make format

      - name: Run lint
        run: make lint

      - name: Extract Pylint Score (from earlier run)
        run: |
          pylint model_training tests | tee pylint_output.txt || true
          SCORE_LINE=$(grep "Your code has been rated at" pylint_output.txt || true)
          SCORE=$(echo "$SCORE_LINE" | sed -E 's/.*rated at ([0-9]+\.[0-9]+)\/10.*/\1/' || true)

          echo "Raw line: $SCORE_LINE"
          echo "Extracted Score: $SCORE"

          if [[ "$SCORE" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
            echo "PYLINT_SCORE=$SCORE" >> $GITHUB_ENV
          else
            echo "Could not extract valid pylint score." >&2
            echo "PYLINT_SCORE=0.0" >> $GITHUB_ENV
          fi

      - name: Download NLTK data
        run: |
          python -m nltk.downloader stopwords wordnet omw-1.4

      - name: Download dataset
        run: python -m model_training.dataset

      - name: Run tests with coverage (detailed output)
        run: |
          echo "Reading model version from dynamic_version.txt..."
          MODEL_VERSION=$(cat dynamic_version.txt)
          echo "Model version: $MODEL_VERSION"

          export PYTHONPATH=$(pwd):$PYTHONPATH

          echo "Running unit tests..."
          coverage run --rcfile=.coveragerc -m pytest -v --tb=short --durations=10 tests | tee test_output.txt

      - name: Debug check for metrics.json
        run: |
          echo "Current directory: $(pwd)"
          ls -lah
          cat $GITHUB_WORKSPACE/metrics.json || echo "metrics.json not found!"

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Extract and update coverage and pylint badges below title
        run: |
          # --- COVERAGE BADGE ---
          COVERAGE=$(tail -n1 coverage.txt | awk '{print $NF}')
          echo "Coverage: ${COVERAGE}"

          COVERAGE_VALUE=$(echo $COVERAGE | tr -d '%')
          if [ "$COVERAGE_VALUE" -ge 90 ]; then
            COV_COLOR="brightgreen"
          elif [ "$COVERAGE_VALUE" -ge 75 ]; then
            COV_COLOR="yellow"
          else
            COV_COLOR="red"
          fi

          COVERAGE_BADGE="![coverage](https://img.shields.io/badge/coverage-${COVERAGE//%/%25}-$COV_COLOR)"

          # --- PYLINT BADGE ---
          # Read score from env if available
          SCORE=${PYLINT_SCORE:-$(grep "Your code has been rated at" pylint_output.txt | grep -oP '\d+\.\d+(?=/10)')}

          echo "Pylint Score: ${SCORE}"

          if (( $(echo "$SCORE >= 9.0" | bc -l) )); then
            PYLINT_COLOR="brightgreen"
          elif (( $(echo "$SCORE >= 7.0" | bc -l) )); then
            PYLINT_COLOR="yellow"
          else
            PYLINT_COLOR="red"
          fi

          ENCODED_SCORE=$(printf "%s" "${SCORE}/10" | sed 's/\//%2F/')
          PYLINT_BADGE="![pylint](https://img.shields.io/badge/pylint-${ENCODED_SCORE}-${PYLINT_COLOR})"


          # --- BADGE UPDATE LOGIC ---
          NEW_BADGES="$COVERAGE_BADGE $PYLINT_BADGE"

          if grep -q '!\[coverage\](https://img.shields.io/badge/coverage-' README.md; then
            awk -v badges="$NEW_BADGES" '
              BEGIN {replaced = 0}
              {
                if (!replaced && $0 ~ /!\[coverage\]\(https:\/\/img\.shields\.io\/badge\/coverage-/) {
                  print badges;
                  replaced = 1;
                } else {
                  print $0;
                }
              }
            ' README.md > README_tmp.md && mv README_tmp.md README.md
          else
            # Insert badges below first non-empty line (title)
            awk -v badges="$NEW_BADGES" '
              NR==1 {print; print ""; print badges; next}
              {print}
            ' README.md > README_tmp.md && mv README_tmp.md README.md
          fi

      - name: Show coverage summary and update README
        run: |
          # Get coverage summary text
          coverage report --rcfile=.coveragerc -m > coverage_summary.txt

          # Define markers
          START_MARKER="<!-- COVERAGE_SUMMARY_START -->"
          END_MARKER="<!-- COVERAGE_SUMMARY_END -->"

          # Remove old summary block
          sed -i "/$START_MARKER/,/$END_MARKER/d" README.md

          # Prepare table header
          {
            echo ""
            echo "$START_MARKER"
            echo ""
            echo "| File | Statements | Miss | Coverage | Missing Lines |"
            echo "|------|------------|------|----------|----------------|"

            # Skip first 2 lines (header and separator), and last line (summary)
            tail -n +3 coverage_summary.txt | sed '$d' | while read -r line; do
              FILE=$(echo "$line" | awk '{print $1}')
              STMT=$(echo "$line" | awk '{print $2}')
              MISS=$(echo "$line" | awk '{print $3}')
              COV=$(echo "$line" | awk '{print $4}')
              MISS_LNS=$(echo "$line" | cut -d' ' -f5-)
              echo "| $FILE | $STMT | $MISS | $COV | $MISS_LNS |"
            done

            echo "$END_MARKER"
          } >> README.md

      - name: Extract test adequacy info and update README
        run: |
          # Remove old section
          sed -i '/<!-- METRICS START -->/,/<!-- METRICS END -->/d' README.md

          echo "<!-- METRICS START -->" >> README.md
          echo "" >> README.md

          # Group by category
          for cat in DATA_AND_FEATURES MODEL_DEVELOPMENT INFRASTRUCTURE_TESTING MONITORING_TESTING; do
            echo "#### ${cat^}" >> README.md
            echo "" >> README.md
            echo "| Metric | Value | Notes |" >> README.md
            echo "|--------|-------|---------|" >> README.md
            jq -r \
              --arg cat "$cat" \
              '. as $root | to_entries
               | map(select(.value.category == $cat))
               | .[] 
               | "| \(.key) | \(.value.value) | \(.value.message // "-") |"' \
               metrics.json >> README.md
            echo "" >> README.md
          done

          echo "<!-- METRICS END -->" >> README.md

      - name: Run mutamorphic test
        run: |
          echo "Reading model version from dynamic_version.txt..."
          MODEL_VERSION=$(cat dynamic_version.txt)
          echo "Model version: $MODEL_VERSION"
          MODEL_PATH="models/$MODEL_VERSION/${MODEL_VERSION}_Sentiment_Model.pkl"


          export PYTHONPATH=$(pwd):$PYTHONPATH
          python tests/test_mutamorphic.py --input data/processed/metamorphic_data.tsv \
            --model-version "$MODEL_PATH"
          echo "Contents of generated CSV file:"
          cat tests/results/mutamorphic_results.csv

      - name: Append mutamorphic results to README
        run: |
          # Define markers
          START_MARKER="<!-- MUTAMORPHIC_RESULTS_START -->"
          END_MARKER="<!-- MUTAMORPHIC_RESULTS_END -->"

          # Remove old block if present
          sed -i "/$START_MARKER/,/$END_MARKER/d" README.md

          {
            echo ""
            echo "$START_MARKER"
            echo ""
            echo "### Metamorphic Test Results"
            echo ""
            echo '| Input | Transformed | Original Prediction | Transformed Prediction | Changed? |'
            echo '|-------|-------------|---------------------|-------------------------|----------|'
            tail -n +2 mutamorphic_results.csv | while IFS=',' read -r a b c d e; do
              echo "| $a | $b | $c | $d | $e |"
            done
            echo ""
            echo "$END_MARKER"
          } >> README.md

      - name: Commit and push updated README
        run: |
          git add README.md
          git diff --cached --quiet || git commit -m "ci: update README with test results"
          git push
