name: Release model-training
on:
    push:
        tags:
            - 'v*.*.*'
            - 'v*.*.*-pre-*' 

jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python 3.12.2
              uses: actions/setup-python@v5
              with:
                  python-version: 3.12.2

            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                version: 1.8.2
                virtualenvs-create: true
                virtualenvs-in-project: true

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  poetry install --no-interaction --no-ansi
                  poetry install --no-interaction --no-ansi setuptools wheel twine
                
            - name: Train and save model
              run: |
                python model-training/modeling/train.py ${{ github.ref_name }}
                    
            - name: Upload to GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                files: |
                  models/${{ github.ref_name }}/*.pkl
                  bow/*.pkl
              env:
                GITHUB_TOKEN: ${{ secrets.OP_TOKEN }}